---
- name: Build LDAP server
  command: docker build -t core_ldap ../docker/ldap

- name: Build phpLDAPadmin server
  command: docker build -t core_phpldapadmin ../docker/phpldapadmin

- name: LDAP container
  docker:
    name: ldap
    image: core_ldap
    state: started
    ports: ["636:636"]
    volumes:
      - "{{ ldap_dir }}/var/lib/openldap:/var/lib/openldap"
      - "{{ ldap_dir }}/var/run/openldap:/var/run/openldap"
      - "{{ ldap_dir }}/etc/openldap:/etc/openldap"
      - "{{ ldap_dir }}/var/log:/var/log"

- name: phpLDAPadmin container
  docker:
    name: phpldapadmin
    image: core_phpldapadmin
    state: started
    links: ["ldap:ldap"]
    ports: ["8636:443"]
    volumes:
      - "{{ phpldapadmin_dir }}/var/log:/var/log"

